version: '3.8'
volumes:
  data:
services:
  db:
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql/data/
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_ROOT_PASSWORD=root
  app:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1